#########################################################
#
#   DEVICE_TRACKERS
#
#########################################################

#----  iCloud iPhone Location Services ------------------------
- platform: icloud3
  username: !secret icloud_username
  password: !secret icloud_password
  account_name: gary_icloud
  include_device_type: iphone

#----- Other Configuration Variables (set to default values) ----
#   include_device:
#     -  ipad_mini
#    include_device_types: 
#       - iphone
#   include_device: lillian_iwatch
#   exclude_devices: 
#     - lillian_iphone
#     - gary_iphone
#   exclude_devices: 
#     - lillian_iphone
#     - connies_ipad
#   exclude_device_types: ipad
#   sensor_name_prefix: name
#   sensor_name_prefix:
#    - gary_iphone @ garyc
#    - lillian_iphone @ lillianc
#   stationary_inzone_interval: '30 min'
#   stationary_still_time: '8 min'
#   gps_accuracy_threshold: 75
#   ignore_gps_accuracy_inzone: False
#   inzone_interval: '2 hrs'
#   travel_time_factor: .6
#   hide_gps_coordinates: false
#   distance_method: calc
#   waze_region: US
#   waze_min_distance: 1
#   waze_max_distance: 9999
#   waze_realtime: False

  